{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-waldo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/waldo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/waldo/waldo_{{ version }}.tar.gz
  sha256: 57ee89eec9bcbba58cf8fa29c8e097f038768c30833eaf812682826333127eaa

build:
  merge_build_host: true  # [win]
  number: 1
  # Only building r packages for win64, linux64, osx64
  skip: True # [aarch64 or s390x or ppc64le or arm64]

  rpaths:
    - lib/R/lib/
    - lib/

  # weird error on windows
  missing_dso_whitelist:
    - $RPATH/R.dll  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base {{ r_version }}
    - r-cli
    - r-diffobj 
    - r-fansi
    - r-glue
    - r-rematch2
    - r-rlang >=1.0.0
    - r-tibble
  run:
    - r-base {{ r_version }}
    - r-cli
    - r-diffobj 
    - r-fansi
    - r-glue
    - r-rematch2
    - r-rlang >=1.0.0
    - r-tibble

test:
  commands:
    - $R -e "library('waldo')"           # [not win]
    - "\"%R%\" -e \"library('waldo')\""  # [win]

about:
  home: https://github.com/r-lib/waldo
  license: MIT
  summary: Compare complex R objects and reveal the key differences.  Designed particularly for use in testing packages where being able to quickly isolate key differences makes understanding test failures much easier.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider
      - ianaobi

# Package: waldo
# Title: Find Differences Between R Objects
# Version: 0.2.2
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Compare complex R objects and reveal the key differences.  Designed particularly for use in testing packages where being able to quickly isolate key differences makes understanding test failures much easier.
# License: MIT + file LICENSE
# URL: https://github.com/r-lib/waldo
# BugReports: https://github.com/r-lib/waldo/issues
# Imports: cli, diffobj, fansi, glue, methods, rematch2, rlang, tibble
# Suggests: testthat, covr, R6
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2020-10-15 19:52:48 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-10-15 21:10:02 UTC
